export const MINI_APPS = [
  {
    id: 'vocabulary',
    title: 'Vocabulary Vault',
    shortTitle: 'Vocabulary',
    description: 'Master 25,000+ words. Track your learning progress anonymously with a persistent Vault Key.',
    icon: 'fas fa-key',
    image: '/images/mini-apps/vocabulary-vault-cover.png',
    href: '/vocabulary',
    status: 'active',
    theme: 'gold',
    badge: 'New',
  },
  {
    id: 'finance',
    title: 'Financial Portfolio',
    shortTitle: 'Finance',
    description: 'Track your assets across stocks, crypto, forex, and gold with real-time market data.',
    icon: 'fas fa-wallet',
    image: '/images/mini-apps/financial-portfolio-cover.png',
    href: '/finance',
    status: 'active',
    theme: 'blue',
    badge: 'Live',
  },
  {
    id: 'snippets',
    title: 'Snippet Vault',
    shortTitle: 'Snippets',
    description: 'A curated collection of useful regex patterns, hooks, and utility functions.',
    icon: 'fas fa-code',
    image: '/images/mini-apps/snippet-vault-cover.png',
    status: 'coming_soon',
    theme: 'blue',
  },
  {
    id: 'pomodoro',
    title: 'Focus Timer',
    shortTitle: 'Focus',
    description: 'Customizable Pomodoro timer with ambient sounds for deep work sessions.',
    icon: 'fas fa-hourglass-half',
    image: '/images/mini-apps/focus-timer-cover.png',
    status: 'coming_soon',
    theme: 'red',
  },
  {
    id: 'palette',
    title: 'Palette Generator',
    shortTitle: 'Palette',
    description: 'Generate beautiful color schemes and export to Tailwind CSS config.',
    icon: 'fas fa-palette',
    image: '/images/mini-apps/palette-generator-cover.png',
    status: 'coming_soon',
    theme: 'pink',
  },
];

export const ACTIVE_MINI_APPS = MINI_APPS.filter((app) => app.status === 'active' && app.href);

const MINI_APP_THEME_PRESETS = {
  gold: {
    accent: '#e8c547',
    accentStrong: '#f4d76b',
    accentText: '#f7d95f',
    pageBg: '#030303',
    chromeBg: 'rgba(6, 6, 8, 0.94)',
    chromeBgSolid: '#050505',
    border: 'rgba(232, 197, 71, 0.18)',
    borderStrong: 'rgba(232, 197, 71, 0.42)',
    surface: 'rgba(255, 255, 255, 0.055)',
    surfaceStrong: 'rgba(255, 255, 255, 0.09)',
    muted: '#8f8c9a',
    glow: 'rgba(232, 197, 71, 0.18)',
    skeletonBase: 'rgba(28, 25, 18, 0.82)',
    skeletonHighlight: 'rgba(76, 64, 34, 0.86)',
    skeletonShine: 'rgba(232, 197, 71, 0.18)',
    skeletonSurface: 'rgba(255, 255, 255, 0.045)',
  },
  blue: {
    accent: '#22d3ee',
    accentStrong: '#67e8f9',
    accentText: '#67e8f9',
    pageBg: '#030712',
    chromeBg: 'rgba(3, 7, 18, 0.94)',
    chromeBgSolid: '#030712',
    border: 'rgba(34, 211, 238, 0.18)',
    borderStrong: 'rgba(34, 211, 238, 0.42)',
    surface: 'rgba(255, 255, 255, 0.055)',
    surfaceStrong: 'rgba(255, 255, 255, 0.09)',
    muted: '#8a96a8',
    glow: 'rgba(34, 211, 238, 0.18)',
    skeletonBase: 'rgba(12, 23, 36, 0.84)',
    skeletonHighlight: 'rgba(20, 64, 84, 0.86)',
    skeletonShine: 'rgba(34, 211, 238, 0.18)',
    skeletonSurface: 'rgba(255, 255, 255, 0.045)',
  },
  red: {
    accent: '#fb7185',
    accentStrong: '#fda4af',
    accentText: '#fda4af',
    pageBg: '#080304',
    chromeBg: 'rgba(8, 3, 4, 0.94)',
    chromeBgSolid: '#080304',
    border: 'rgba(251, 113, 133, 0.18)',
    borderStrong: 'rgba(251, 113, 133, 0.42)',
    surface: 'rgba(255, 255, 255, 0.055)',
    surfaceStrong: 'rgba(255, 255, 255, 0.09)',
    muted: '#9a8c93',
    glow: 'rgba(251, 113, 133, 0.18)',
    skeletonBase: 'rgba(34, 15, 18, 0.84)',
    skeletonHighlight: 'rgba(88, 32, 42, 0.86)',
    skeletonShine: 'rgba(251, 113, 133, 0.18)',
    skeletonSurface: 'rgba(255, 255, 255, 0.045)',
  },
  pink: {
    accent: '#f472b6',
    accentStrong: '#f9a8d4',
    accentText: '#f9a8d4',
    pageBg: '#08030a',
    chromeBg: 'rgba(8, 3, 10, 0.94)',
    chromeBgSolid: '#08030a',
    border: 'rgba(244, 114, 182, 0.18)',
    borderStrong: 'rgba(244, 114, 182, 0.42)',
    surface: 'rgba(255, 255, 255, 0.055)',
    surfaceStrong: 'rgba(255, 255, 255, 0.09)',
    muted: '#9a8a99',
    glow: 'rgba(244, 114, 182, 0.18)',
    skeletonBase: 'rgba(33, 16, 36, 0.84)',
    skeletonHighlight: 'rgba(78, 34, 72, 0.86)',
    skeletonShine: 'rgba(244, 114, 182, 0.18)',
    skeletonSurface: 'rgba(255, 255, 255, 0.045)',
  },
};

export function getMiniAppTheme(app) {
  const theme = MINI_APP_THEME_PRESETS[app?.theme] || MINI_APP_THEME_PRESETS.gold;

  return {
    ...theme,
    cssVars: {
      '--mini-accent': theme.accent,
      '--mini-accent-strong': theme.accentStrong,
      '--mini-accent-text': theme.accentText,
      '--mini-page-bg': theme.pageBg,
      '--mini-chrome-bg': theme.chromeBg,
      '--mini-chrome-bg-solid': theme.chromeBgSolid,
      '--mini-border': theme.border,
      '--mini-border-strong': theme.borderStrong,
      '--mini-surface': theme.surface,
      '--mini-surface-strong': theme.surfaceStrong,
      '--mini-muted': theme.muted,
      '--mini-glow': theme.glow,
      '--skeleton-base': theme.skeletonBase,
      '--skeleton-highlight': theme.skeletonHighlight,
      '--skeleton-shine': theme.skeletonShine,
      '--skeleton-surface': theme.skeletonSurface,
      '--skeleton-border': theme.border,
    },
  };
}

export function getMiniAppByPathname(pathname) {
  if (!pathname) return null;
  return ACTIVE_MINI_APPS.find((app) => pathname === app.href || pathname.startsWith(`${app.href}/`)) || null;
}
